# Generated by Django 5.2.7 on 2025-11-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postvisit_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvisit',
            name='duration_seconds',
        ),
    ]
